title: Miguel Viera's blog
description: >-
  This is my personal blog. This is an experiment 
lang: en-GB
timezone: Europe/Spain # set your timezone
image: assets/img/ogp.png
repo: https://github.com/mangelviera/mangelviera.github.io
mode: dark

# Profile settings
author:
  name: Miguel Ángel Viera
  bio: >- 
    I'm Miguel Viera, welcome to my personal blog. 
    Hope you can find something useful.
    Any feedback is welcome, you can know more about me on: <a href="/about">about</a> 
  username: mangelviera
  github: mangelviera
  twitter: mangelviera
  email: mangelviera93@me.com
  avatar: /assets/img/avatar.jpg

url: "mangelviera.com"
baseurl:
permalink: /:title/
google_analytics: # leave it blank if not wish

collections:
  posts:
    output: true

markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: true

jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 15


sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
